# Generated by Django 2.2 on 2020-02-20 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DojoReads_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='users_rates',
        ),
    ]
